/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;


import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author emree
 */
public class RegisterController extends javax.swing.JFrame {
  Connection con=null;
    /**
     * Creates new form LoginController
     */
    public RegisterController() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserLabel2 = new javax.swing.JLabel();
        UserTxt2 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PassLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        SurnameTxt = new javax.swing.JTextField();
        RegisterButton = new java.awt.Button();
        TCLabel = new javax.swing.JLabel();
        TcTxt = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        UserTxt = new javax.swing.JTextField();
        MailLabel = new javax.swing.JLabel();
        MailTxt = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        UserLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        UserLabel2.setForeground(new java.awt.Color(204, 204, 255));
        UserLabel2.setText("User Name :");

        UserTxt2.setBackground(new java.awt.Color(187, 187, 252));
        UserTxt2.setForeground(new java.awt.Color(40, 98, 136));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 98, 136));

        jPanel2.setBackground(new java.awt.Color(40, 98, 136));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 36), new java.awt.Color(115, 147, 179))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(134, 134, 188));

        PassLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        PassLabel.setForeground(new java.awt.Color(204, 204, 255));
        PassLabel.setText("Password");

        SurnameLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        SurnameLabel.setForeground(new java.awt.Color(204, 204, 255));
        SurnameLabel.setText("Surname :");

        SurnameTxt.setBackground(new java.awt.Color(187, 187, 252));
        SurnameTxt.setForeground(new java.awt.Color(40, 98, 136));

        RegisterButton.setActionCommand("LoginButton");
        RegisterButton.setBackground(new java.awt.Color(153, 153, 255));
        RegisterButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(204, 204, 255));
        RegisterButton.setLabel("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        TCLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        TCLabel.setForeground(new java.awt.Color(204, 204, 255));
        TCLabel.setText("T.C :");

        TcTxt.setBackground(new java.awt.Color(187, 187, 252));
        TcTxt.setForeground(new java.awt.Color(40, 98, 136));

        UserLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(204, 204, 255));
        UserLabel.setText("User Name :");

        UserTxt.setBackground(new java.awt.Color(187, 187, 252));
        UserTxt.setForeground(new java.awt.Color(40, 98, 136));

        MailLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        MailLabel.setForeground(new java.awt.Color(204, 204, 255));
        MailLabel.setText("Mail :");

        MailTxt.setBackground(new java.awt.Color(187, 187, 252));
        MailTxt.setForeground(new java.awt.Color(40, 98, 136));

        NameLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(204, 204, 255));
        NameLabel.setText("Name :");

        NameTxt.setBackground(new java.awt.Color(187, 187, 252));
        NameTxt.setForeground(new java.awt.Color(40, 98, 136));

        PasswordField1.setBackground(new java.awt.Color(187, 187, 252));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("I already have an account");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameLabel)
                    .addComponent(SurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel)
                    .addComponent(UserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(MailLabel)
                    .addComponent(TcTxt)
                    .addComponent(TCLabel)
                    .addComponent(PasswordField1))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(237, 237, 237))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TCLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SurnameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(UserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public void infoMessage(String message, String tittle){
        JOptionPane.showMessageDialog(null,message,tittle,JOptionPane.INFORMATION_MESSAGE);
        
    }
    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        
        String firstname=NameTxt.getText();
        String lastname=SurnameTxt.getText();
        int   tc=Integer.parseInt(TcTxt.getText());
        String mail=MailTxt.getText();
        String surname= UserTxt.getText();
        String password= PasswordField1.getText();
        
        
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String databaseURL="jdbc:mysql://localhost:3306/ucak_bileti";
            con=(Connection) DriverManager.getConnection(databaseURL,"root","");
            
            Statement stat = con.createStatement();
            
            String selectQuery="select count(*) from user_details where username='"+surname+"' and password='"+password+"'";
            ResultSet rs=stat.executeQuery(selectQuery);
            System.out.println(rs.next());
            if(rs.next()==true){
                infoMessage("Already Registered ","Welcome Bro !!");
            }
            else{
                 String insertQuery="insert into user_details values(null,'"+firstname+"','"+lastname+"','"+tc+"','"+mail+"','"+surname+"','"+password+"')";
            
           stat.executeUpdate(insertQuery);
                        infoMessage("Information is inserted ","Welcome Bro !!");

                dispose();
             setVisible(false);
        UserMain login =new UserMain();
        login.setVisible(true);
                
            
            }
           
        } catch (Exception e) {
            System.out.println(e);
        }
       
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        LoginController lc = new LoginController();
        lc.setVisible(true);
        lc.pack();
        lc.setLocationRelativeTo(null);
        lc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MailLabel;
    private javax.swing.JTextField MailTxt;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPasswordField PasswordField1;
    private java.awt.Button RegisterButton;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JTextField SurnameTxt;
    private javax.swing.JLabel TCLabel;
    private javax.swing.JTextField TcTxt;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel2;
    private javax.swing.JTextField UserTxt;
    private javax.swing.JTextField UserTxt2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}

